name: Build electron app and release

on:
  push:
    # branches:
    #   - master
    tags:
      - v*
jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest] #, ubuntu-latest, windows-latest]
        node-version: [14.x]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
      - name: Set up nodejs
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Install dependencies using Node.js ${{ matrix.node-version }}
        run: yarn install
      - name: Build/release Electron app
        uses: samuelmeuli/action-electron-builder@v1
        with:
          # GitHub token, automatically provided to the action
          # (No need to define this secret in the repo settings)
          github_token: ${{ secrets.github_token }}

          # If the commit is tagged with a version (e.g. "v1.0.0"),
          # release the app after building
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}

          package_root: applications/jupyter-app
          build_script_name: "build-all"
